[package]
name = "empire"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lucasvienna/empire.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
logs-wheel = "0.3.1"
diesel = { version = "2.2.6", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
diesel_migrations = "2.2.0"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
chrono = "0.4.39"
anyhow = "1.0.94"
