[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lucasvienna/empire.git"
readme = "README.md"
publish = false

[package]
name = "empire"
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "empire"

[dependencies]
anyhow = { workspace = true }
axum = { version = "0.7.9", features = ["query", "macros"] }
axum-test = { version = "16.4.1", features = ["all"] }
chrono = "0.4.39"
diesel = { version = "2.2.6", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
http-body-util = "0.1.2"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
logs-wheel = "0.3.1"
mime = "0.3.17"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { workspace = true }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[workspace]
members = [
    ".",
    "crates/rpc"
]

[workspace.dependencies]
anyhow = "1.0.95"
empire = { path = "." }
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
