[package]
name = "empire"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lucasvienna/empire.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.1", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
diesel_migrations = "2.2.0"
libsqlite3-sys = { version = "0.28.0", features = ["bundled"] }
dotenvy = "0.15.7"
log4rs = "1.3.0"
log = "0.4.22"
thiserror = "1.0.62"
anyhow = "1.0.86"
