name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  DIESEL_VERSION: 2.3.3
  DIESEL_FEATURES: "postgres"
  APP_DATABASE__USERNAME: test
  APP_DATABASE__PASSWORD: test
  APP_DATABASE__DATABASE_NAME: empire_test
  PGPASSWORD: password

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          diesel_version: ${{ env.DIESEL_VERSION }}
          diesel_features: ${{ env.DIESEL_FEATURES }}
          app_user: ${{ env.APP_DATABASE__USERNAME }}
          app_pwd: ${{ env.APP_DATABASE__PASSWORD }}
          pgpassword: ${{ env.PGPASSWORD }}
      - name: Run tests
        run: cargo test -- --test-threads=1

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: { components: rustfmt }
      - name: rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: { components: clippy }
      - name: Linting
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v6
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: { components: llvm-tools-preview }
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          diesel_version: ${{ env.DIESEL_VERSION }}
          diesel_features: ${{ env.DIESEL_FEATURES }}
          app_user: ${{ env.APP_DATABASE__USERNAME }}
          app_pwd: ${{ env.APP_DATABASE__PASSWORD }}
          pgpassword: ${{ env.PGPASSWORD }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov test --all-features --workspace --lcov --output-path lcov.info -- --test-threads=1
      - name: Generate report
        run: cargo llvm-cov report --html --output-dir coverage
      - uses: actions/upload-artifact@v7
        with:
          name: "Coverage report"
          path: coverage/
